services:
  - type: web
    name: betabox-describinator
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python setup_models.py && python run_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MODEL_URL
        sync: false
      - key: DCGAN_URL
        sync: false
    healthCheckPath: /
